# Generated by Django 5.2 on 2026-06-15 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_setupchecklistdismissal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupchecklistdismissal',
            options={'verbose_name': 'Setup Checklist Dismissal', 'verbose_name_plural': 'Setup Checklist Dismissals'},
        ),
        migrations.AddField(
            model_name='setupchecklistdismissal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_checklist_dismissals', to='base.company'),
        ),
        migrations.AlterField(
            model_name='setupchecklistdismissal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_checklist_dismissals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='setupchecklistdismissal',
            unique_together={('user', 'company')},
        ),
    ]
